Repository LIS/lis-test, pull requests merged in 2018-09, with the labels that each got.

#1105 Add uio TC to all BVT/FVT
  WS2012R2/lisa/remote-scripts/ica/UIO_Basic.sh
  WS2012R2/lisa/xml/hyperv_bvt.xml
  WS2012R2/lisa/xml/hyperv_fvt.xml
  WS2012R2/lisa/xml/kernel_pipeline_bvt.xml
  WS2012R2/lisa/xml/kernel_pipeline_fvt.xml
  WS2012R2/lisa/xml/lis_pipeline_bvt.xml
  WS2012R2/lisa/xml/lis_pipeline_fvt.xml
  WS2012R2/lisa/xml/ubuntu_azure_kernel_fvt.xml
Labels: test-case

#1106 CDmount test case refresh
  WS2012R2/lisa/setupscripts/InsertIsoInDvd.ps1
  WS2012R2/lisa/setupscripts/RemoveIsoFromDvd.ps1
  WS2012R2/lisa/xml/CoreTests.xml
  WS2012R2/lisa/xml/lis_pipeline_fvt.xml
Labels: enhancement

#1109 SR-IOV param update
  WS2012R2/lisa/setupscripts/NET_UTILS.ps1
  WS2012R2/lisa/setupscripts/SR-IOV_MoveVHD.ps1
  WS2012R2/lisa/xml/SR-IOV.xml
  WS2012R2/lisa/xml/kernel_pipeline_sriov.xml
Labels: enhancement

#1115 Stress test: Fail if event id 18602 is triggered by VM start/stop loop
  WS2012R2/lisa/setupscripts/MultipleReboot.ps1
  WS2012R2/lisa/setupscripts/eventid_18602_regression.ps1
  WS2012R2/lisa/xml/StressTests.xml
Labels: enhancement, test-case
