Repository LIS/lis-test, pull requests merged in 2018-05, with the labels that each got.

#1013 Hv_Sock refactorig
  WS2012R2/lisa/setupscripts/HV_Sock_Basic.ps1
  WS2012R2/lisa/xml/HV_Sock.xml
Labels: enhancement, hv-sock

#1009 Ethtool statistics test case
  WS2012R2/lisa/remote-scripts/ica/Ethtool_Check_Statistics.sh
  WS2012R2/lisa/remote-scripts/ica/netperf_client.sh
  WS2012R2/lisa/remote-scripts/ica/netperf_server.sh
  WS2012R2/lisa/xml/NET_Tests.xml
  WS2012R2/lisa/xml/PERF_Netperf.xml
Labels: test-case

#1017 refactor test cases with GrowFS on VhdXResize
  WS2012R2/lisa/remote-scripts/ica/STOR_VHDXResize_GrowFSAfterResize.sh
  WS2012R2/lisa/setupscripts/STOR_VHDXResize_GrowFS.ps1
Labels: enhancement

#1010 Add new feature: debugScript
  WS2012R2/lisa/DebugScript.ps1
  WS2012R2/lisa/lisa.ps1
  WS2012R2/lisa/stateEngine.ps1
  WS2012R2/lisa/utilFunctions.ps1
Labels: feature

#1024 Modified Live Migration tests
  WS2012R2/lisa/xml/NET_LIVEMIG.xml
Labels: enhancement, test-case

#1036 fix for Debian
  WS2012R2/lisa/remote-scripts/ica/NET_Corruption.sh
Labels: enhancement
