Repository LIS/lis-test, pull requests merged in 2018-06, with the labels that each got.

#1037 LTP testcase updates
  WS2012R2/lisa/remote-scripts/ica/LTP_test.sh
  WS2012R2/lisa/xml/LTP.xml
Labels: enhancement

#1032 Add new test case for hot add dvd
  WS2012R2/lisa/remote-scripts/ica/Core_LIS_CD.sh
  WS2012R2/lisa/setupscripts/InsertIsoInDvd.ps1
  WS2012R2/lisa/xml/CoreTests.xml
Labels: test-case

#1046 Tune Nginx and Kernel configuration to allow more connections and minor fix some code
  WS2012R2/lisa/tools/middleware_bench/suites/middleware.py
  WS2012R2/lisa/tools/middleware_bench/tests/install_lemp_wordpress.sh
  WS2012R2/lisa/tools/middleware_bench/tests/perf_tuning.sh
  WS2012R2/lisa/tools/middleware_bench/utils/list_suite_cases.py
  WS2012R2/lisa/tools/middleware_bench/utils/setup.py
Labels: performance_automation

#1042 Add clockevent check case
  WS2012R2/lisa/remote-scripts/ica/check_clockevent.sh
  WS2012R2/lisa/xml/CoreTests.xml
Labels: test-case

#1052 minor changes on FC Tests
  WS2012R2/lisa/remote-scripts/ica/FC_disks.sh
  WS2012R2/lisa/setupscripts/FC_AddFibreChannelHba.ps1
  WS2012R2/lisa/xml/FC_Tests.xml
Labels: enhancement

#1056 Add clockevent check on SMP CPUs
  WS2012R2/lisa/remote-scripts/ica/Core_Time_Clockevent.sh
  WS2012R2/lisa/remote-scripts/ica/Core_Time_Clocksource.sh
  WS2012R2/lisa/remote-scripts/ica/check_clocksource.sh
  WS2012R2/lisa/xml/CoreTests.xml
Labels: test-case

#1059 ifdown-ifup regression test case
  WS2012R2/lisa/remote-scripts/ica/verify_ifdown_ifup.sh
  WS2012R2/lisa/xml/NET_Tests.xml
Labels: test-case

#1060 update kexec-tools before testing kdump
  WS2012R2/lisa/remote-scripts/ica/Kdump_Config.sh
Labels: enhancement

#1054 KVP basic test case - permissions and lsof checks additions
  WS2012R2/lisa/remote-scripts/ica/KVP_BasicTest.sh
  WS2012R2/lisa/xml/KvpTests.xml
  WS2012R2/lisa/xml/RDOS_WS2012.xml
Labels: enhancement

#1045 Dynamically create backup disk and add functionality for creating multiple VHDX disks with different FSs
  WS2012R2/lisa/remote-scripts/ica/PartitionMultipleDisks.sh
  WS2012R2/lisa/setupscripts/Cleanup_Backup_Disk.ps1
  WS2012R2/lisa/setupscripts/RevertSnapshot.ps1
  WS2012R2/lisa/setupscripts/STOR_VSS_3Chain_VHD_backup.ps1
  WS2012R2/lisa/setupscripts/STOR_VSS_BackupRestore_DiskStress.ps1
  WS2012R2/lisa/setupscripts/STOR_VSS_BackupRestore_Fail.ps1
  WS2012R2/lisa/setupscripts/STOR_VSS_BackupRestore_ISCSI.ps1
  WS2012R2/lisa/setupscripts/STOR_VSS_BackupRestore_ISO_NoNetwork.ps1
  WS2012R2/lisa/setupscripts/STOR_VSS_BackupRestore_Mount_Multi_Paths.ps1
  WS2012R2/lisa/setupscripts/STOR_VSS_BackupRestore_Mount_Squashfs.ps1
  WS2012R2/lisa/setupscripts/STOR_VSS_BackupRestore_Partition.ps1
  WS2012R2/lisa/setupscripts/STOR_VSS_BackupRestore_State.ps1
  WS2012R2/lisa/setupscripts/STOR_VSS_Backup_Change_Hypervvssd.ps1
  WS2012R2/lisa/setupscripts/STOR_VSS_Backup_Disable_Enable_VSS.ps1
  WS2012R2/lisa/setupscripts/STOR_VSS_Utils.ps1
  WS2012R2/lisa/setupscripts/Setup_Backup_Disk.ps1
  WS2012R2/lisa/setupscripts/TCUtils.ps1
  WS2012R2/lisa/xml/STOR_VSS_Backup_Tests_Dynamic_VHDX.xml
Labels: feature, test-case

#1067 VSS automation fixes
  WS2012R2/lisa/remote-scripts/ica/STOR_VSS_Set_VSS_Daemon.sh
  WS2012R2/lisa/setupscripts/STOR_VSS_Utils.ps1
  WS2012R2/lisa/setupscripts/TCUtils.ps1
  WS2012R2/lisa/xml/STOR_VSS_Backup_Tests_Dynamic_VHDX.xml
  WS2012R2/lisa/xml/VSS_Backup.xml
Labels: enhancement
