Repository LIS/lis-test, pull requests merged in 2018-10, with the labels that each got.

#1117 install_kernel: remove grub-legacy-ec2 on Debian
  WS2012R2/lisa/remote-scripts/ica/install_kernel.sh
Labels: bug

#1124 Updated Production_checkpoint_ISO_NoNetwork .ps1 : Get test CD from URL
  WS2012R2/lisa/setupscripts/Production_checkpoint_ISO_NoNetwork.ps1
Labels: enhancement

#1125 Updated NET_BootNoNICHotAddNIC.ps1
  WS2012R2/lisa/setupscripts/NET_BootNoNICHotAddNIC.ps1
Labels: bug

#1126 Kdump_Config.sh: fix can not find kernel command in grub.cfg issue an…
  WS2012R2/lisa/remote-scripts/ica/Kdump_Config.sh
  WS2012R2/lisa/remote-scripts/ica/Kdump_Execute.sh
Labels: enhancement

#1121 Lcow testing
  WS2012R2/lisa/remote-scripts/ica/LTP_test.sh
  WS2012R2/lisa/remote-scripts/ica/install_lcow_kernel.sh
  WS2012R2/lisa/xml/lcow_fvt.xml
Labels: feature

#1130 lsvmbus: Fix core spread issue
  WS2012R2/lisa/remote-scripts/ica/lsvmbus_target.sh
  WS2012R2/lisa/xml/hyperv_bvt.xml
  WS2012R2/lisa/xml/hyperv_fvt.xml
  WS2012R2/lisa/xml/kernel_pipeline_bvt.xml
  WS2012R2/lisa/xml/lis_pipeline_bvt.xml
  WS2012R2/lisa/xml/lsvmbus.xml
Labels: enhancement

#1132 SR-IOV: Common bash script for all basic tests
  WS2012R2/lisa/remote-scripts/ica/SR-IOV_MaxNIC.sh
  WS2012R2/lisa/remote-scripts/ica/SR-IOV_Multiple_basic.sh
  WS2012R2/lisa/remote-scripts/ica/SR-IOV_Multiple_fileCopy.sh
  WS2012R2/lisa/remote-scripts/ica/SR-IOV_Utils.sh
  WS2012R2/lisa/remote-scripts/ica/SR-IOV_VerifyVF_basic.sh
  WS2012R2/lisa/xml/SR-IOV.xml
  WS2012R2/lisa/xml/kernel_pipeline_sriov.xml
Labels: enhancement
