Repository LIS/lis-test, pull requests merged in 2018-03, with the labels that each got.

#930 Update StateEngine and utilFunctions to fix xml error when running di…
  WS2012R2/lisa/stateEngine.ps1
  WS2012R2/lisa/utilFunctions.ps1
Labels: enhancement

#941 VM state file separation
  WS2012R2/lisa/stateEngine.ps1
Labels: enhancement

#945 fixed sector sizes for vhdx
  WS2012R2/lisa/setupscripts/AddVhdxHardDisk.ps1
Labels: enhancement

#947 KVP_Max_Read: skip kernel version below 3.10.3.860 (RHEL7.5)
  WS2012R2/lisa/setupscripts/KVP_Max_Read.ps1
  WS2012R2/lisa/setupscripts/TCUtils.ps1
Labels: enhancement

#929 Sync lisa noshutdown and middlware fixes
  WS2012R2/lisa/Infrastructure/lisa-parser/lisa_parser/file_parser.py
  WS2012R2/lisa/Infrastructure/lisa-parser/lisa_parser/lisa_parser.py
  WS2012R2/lisa/Infrastructure/lisa-parser/lisa_parser/sql_utils.py
  WS2012R2/lisa/Infrastructure/lisa-parser/lisa_parser/test_run.py
  WS2012R2/lisa/lisa.ps1
  WS2012R2/lisa/remote-scripts/ica/Performance_FIO.sh
  WS2012R2/lisa/remote-scripts/ica/perf_iperf_client.sh
  WS2012R2/lisa/remote-scripts/ica/perf_iperf_server.sh
  WS2012R2/lisa/remote-scripts/ica/perf_ntttcp_client.sh
  WS2012R2/lisa/remote-scripts/ica/perf_ntttcp_server.sh
  WS2012R2/lisa/remote-scripts/ica/perf_utils.sh
  WS2012R2/lisa/remote-scripts/ica/utils.sh
  WS2012R2/lisa/stateEngine.ps1
  WS2012R2/lisa/tools/middleware_bench/connector.py
  WS2012R2/lisa/tools/middleware_bench/providers/amazon_service.py
  WS2012R2/lisa/tools/middleware_bench/providers/azure_service.py
  WS2012R2/lisa/tools/middleware_bench/providers/gcp_service.py
  WS2012R2/lisa/tools/middleware_bench/report/db_utils.py
Labels: enhancement

#949 Minor update sleep time make case more robust
  WS2012R2/lisa/setupscripts/INST_LIS_TimeSyncServiceDisableEnable.ps1
  WS2012R2/lisa/setupscripts/Kdump.ps1
Labels: enhancement

#936 Add hv-sock test case: HV_Sock_Basic
  WS2012R2/lisa/setupscripts/HV_Sock_Basic.ps1
  WS2012R2/lisa/tools/hv-sock/README
  WS2012R2/lisa/tools/hv-sock/client_on_host.cpp
  WS2012R2/lisa/tools/hv-sock/client_on_vm.c
  WS2012R2/lisa/tools/hv-sock/server_on_host.cpp
  WS2012R2/lisa/tools/hv-sock/server_on_vm.c
  WS2012R2/lisa/xml/HV_Sock.xml
Labels: hv-sock

#951 Added compiled executables for hv_sock test cases
  WS2012R2/lisa/tools/hv-sock/client_on_host.exe
  WS2012R2/lisa/tools/hv-sock/md5sum.txt
  WS2012R2/lisa/tools/hv-sock/server_on_host.exe
Labels: hv-sock

#958 Multicast TC: Added ethtool allmulti option
  WS2012R2/lisa/remote-scripts/ica/NET_Multicast.sh
  WS2012R2/lisa/remote-scripts/ica/SR-IOV_Multicast.sh
Labels: enhancement

#960 Shielded VMs: Various fixes
  WS2012R2/lisa/remote-scripts/ica/shielded_deployed_functions.sh
  WS2012R2/lisa/setupscripts/Shielded_DEP.ps1
  WS2012R2/lisa/setupscripts/Shielded_PRE-TDC.Tests.ps1
  WS2012R2/lisa/setupscripts/Shielded_PRE-TDC.ps1
  WS2012R2/lisa/setupscripts/Shielded_PRO.Tests.ps1
  WS2012R2/lisa/setupscripts/Shielded_PRO.ps1
Labels: Linux Shielded VM

#962 SR-IOV check for mlx4_core or mlx4_en
  WS2012R2/lisa/remote-scripts/ica/SR-IOV_Utils.sh
  WS2012R2/lisa/remote-scripts/ica/perf_utils.sh
  WS2012R2/lisa/setupscripts/SR-IOV_Deattach_NIC.ps1
  WS2012R2/lisa/setupscripts/SR-IOV_DisableNIC.ps1
Labels: enhancement
